# conda environments:
#
base                     C:\Anaconda3
fastapi_tut              C:\Anaconda3\envs\fastapi_tut
fwr6307                  C:\Anaconda3\envs\fwr6307
leanreview               C:\Anaconda3\envs\leanreview
nafraleanreviewtool      C:\Anaconda3\envs\nafraleanreviewtool
productive_python     *  C:\Anaconda3\envs\productive_python
website                  C:\Anaconda3\envs\website

